resolves #38 replace close option by destroy
pinojs/pino-socket pull request #75
Opened 2022-07-23 23:00 UTC by Mogztter

Not sure how to test but `close` is not a valid option: https://nodejs.org/api/stream.html#new-streamreadableoptions

resolves #38

2022-07-24 07:06 UTC, mcollina requested changes
Thanks for opening a PR! Can you please add a unit test?

2022-07-24 09:22 UTC, Mogztter commented
I don't know how to add a unit test without exporting the socket object (i.e., public accessor) to make sure that the socket was destroyed when the writable stream is closed.

Alternatively, I can add a new option `onSocketDestroyed` (callback function) called after `socket.destroy`?

Thoughts?

2022-07-24 17:42 UTC, mcollina commented
Export the socket.

2022-07-24 19:41 UTC, Mogztter commented
Unit test added!

2022-07-25 07:54 UTC, mcollina approved these changes
lgtm

2022-07-25 07:54 UTC, merged